/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:074978b0-b73c-456f-8e80-bc38d51b37a2",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_G7JWC5OkO",
    "aws_user_pools_web_client_id": "13lfkvk5rq129rai880up437ti",
    "oauth": {}
};


export default awsmobile;
